baseURL = "https://coaching.begbie.com/"
languageCode = "en-gb"
paginate = 6
theme = "portio"
title = "Rod Begbie"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1

[[menu.main]]
name = "About"
url = "#about"
weight = 2


[[menu.main]]
name = "Résumé"
url = "#resume"
weight = 5

[[menu.main]]
name = "Writing"
url = "blog"
weight = 6

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "mailto:rod@begbie.com"
copyright = "Copyright © Rod Begbie 2026"
footerLogo = "images/contact/widget-logo.png"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"
subtitle = "Software Engineering Leadership Coach"

[params.address]
address = "Barcelona, Spain"
email = "rod@begbie.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(448) 833 5272 332"

# Social icons

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/rodbegbie"
weight = 2

[[params.social]]
icon = "fa-bluesky"
url = "https://bsky.app/profile/rod.begbie.com"
weight = 4
