baseURL = "https://coaching.begbie.com/"
languageCode = "en-gb"
theme = "portio"
title = "Rod Begbie"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[pagination]
pagerSize = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1

[[menu.main]]
name = "About"
url = "#about"
weight = 2


[[menu.main]]
name = "Résumé"
url = "#resume"
weight = 5

[[menu.main]]
name = "Writing"
url = "blog"
weight = 6

[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

[params]
blogPageURL = "blog"
contactLink = "mailto:rod@begbie.com"
copyright = "Copyright © Rod Begbie 2026"
footerLogo = "images/contact/widget-logo.png"
logo = "images/site-navigation/logo.png"
subtitle = "Software Engineering Leadership Coach"

# Social icons

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/rodbegbie"
weight = 2

[[params.social]]
icon = "fa-bluesky"
url = "https://bsky.app/profile/rod.begbie.com"
weight = 4
